packages: []

allowBuilds:
  es5-ext: true

patchedDependencies:
  abcjs@6.6.2: patches/abcjs@6.6.2.patch
  katex@0.16.47: patches/katex@0.16.47.patch
  react-plotly.js@2.6.0: patches/react-plotly.js@2.6.0.patch
