import type { BuiltInSpectrumType } from '../types';

export const DEFAULT_SYNTH_OSCILLATOR_TYPE: OscillatorType = 'sine';
export const DEFAULT_SYNTH_VOLUME_RATIO = 0.2;
export const DEFAULT_SYNTH_HARMONIC_COUNT = 10;

export const DEFAULT_ENVELOPE_ATTACK_TIME_SECONDS = 0.01;
export const DEFAULT_ENVELOPE_DECAY_TIME_SECONDS = 0.2;
export const DEFAULT_ENVELOPE_RELEASE_TIME_SECONDS = 0.8;
export const DEFAULT_ENVELOPE_SUSTAIN_GAIN = 0.5;
export const DEFAULT_ENVELOPE_SILENCE_GAIN = 0.00001;

export const DEFAULT_SPECTRUM_TYPE: BuiltInSpectrumType = 'ethereal';
export const DEFAULT_SPECTRUM_STRIKE_POINT = 0.5;
export const DEFAULT_SPECTRUM_DECAY_RATE = 0.8;
export const DEFAULT_SPECTRUM_POWER_EXPONENT = 1.5;

export const DEFAULT_FILTER_EFFECT_TYPE = 'lowpass';
export const DEFAULT_FILTER_EFFECT_FREQUENCY = 1000;
export const DEFAULT_FILTER_EFFECT_Q = 1;

export const DEFAULT_EQUALIZER_EFFECT_TYPE = 'lowshelf';
export const DEFAULT_EQUALIZER_EFFECT_FREQUENCY = 1000;
export const DEFAULT_EQUALIZER_EFFECT_Q = 1;
export const DEFAULT_EQUALIZER_EFFECT_GAIN = 0;

export const DEFAULT_REVERB_EFFECT_PRESET = 'bathroom';
export const DEFAULT_REVERB_EFFECT_MIX = 0.25;
export const DEFAULT_REVERB_EARLY_REFLECTION_DELAY = 0.01;
export const DEFAULT_REVERB_EARLY_REFLECTION_GAIN = 0.5;
export const DEFAULT_REVERB_LATE_TAIL_DURATION = 0.45;
export const DEFAULT_REVERB_LATE_TAIL_AMPLITUDE = 0.32;
export const DEFAULT_REVERB_LATE_TAIL_ALPHA = 0.00035;
