import type {
  BuiltInFilterEqualizerPreset,
  BuiltInReverbPreset,
  BuiltInSpectrumType,
  EqualizerType,
  FilterType,
  WaveShaperPreset,
} from '../types';

export const DEFAULT_SYNTH_OSCILLATOR_TYPE: OscillatorType = 'sine';
export const DEFAULT_SYNTH_VOLUME_RATIO = 0.2;
export const DEFAULT_SYNTH_HARMONIC_COUNT = 10;

export const DEFAULT_ENVELOPE_ATTACK_TIME_SECONDS = 0.01;
export const DEFAULT_ENVELOPE_DECAY_TIME_SECONDS = 0.2;
export const DEFAULT_ENVELOPE_RELEASE_TIME_SECONDS = 0.8;
export const DEFAULT_ENVELOPE_SUSTAIN_GAIN = 0.5;
export const DEFAULT_ENVELOPE_SILENCE_GAIN = 0.00001;

export const DEFAULT_SPECTRUM_TYPE: BuiltInSpectrumType = 'ethereal';
export const DEFAULT_SPECTRUM_STRIKE_POINT = 0.5;
export const DEFAULT_SPECTRUM_DECAY_RATE = 0.8;
export const DEFAULT_SPECTRUM_POWER_EXPONENT = 1.5;

export const DEFAULT_FILTER_TYPE: FilterType = 'lowpass';
export const DEFAULT_FILTER_FREQUENCY = 1000;
export const DEFAULT_FILTER_Q = 1;

export const DEFAULT_EQUALIZER_TYPE: EqualizerType = 'lowshelf';
export const DEFAULT_EQUALIZER_FREQUENCY = 1000;
export const DEFAULT_EQUALIZER_Q = 1;
export const DEFAULT_EQUALIZER_GAIN = 0;
export const DEFAULT_FILTER_EQUALIZER_PRESET: BuiltInFilterEqualizerPreset =
  'classical';

export const DEFAULT_COMPRESSOR_THRESHOLD = -24;
export const DEFAULT_COMPRESSOR_KNEE = 30;
export const DEFAULT_COMPRESSOR_RATIO = 12;
export const DEFAULT_COMPRESSOR_ATTACK = 0.003;
export const DEFAULT_COMPRESSOR_RELEASE = 0.25;

export const DEFAULT_AMPLITUDE_MODULATION_FREQUENCY = 5;
export const DEFAULT_AMPLITUDE_MODULATION_DEPTH = 0.25;

export const DEFAULT_FREQUENCY_MODULATION_FREQUENCY = 5;
export const DEFAULT_FREQUENCY_MODULATION_DEPTH = 20;

export const DEFAULT_PHASE_MODULATION_FREQUENCY = 0.5;
export const DEFAULT_PHASE_MODULATION_DEPTH = 0.5;

export const DEFAULT_DELAY_MODULATION_FREQUENCY = 0.3;
export const DEFAULT_DELAY_MODULATION_DEPTH = 0.008;

export const DEFAULT_WAVE_SHAPER_PRESET: WaveShaperPreset = 'saturation';
export const DEFAULT_WAVE_SHAPER_SATURATION = 0.5;
export const DEFAULT_WAVE_SHAPER_DISTORTION = 5;
export const DEFAULT_WAVE_SHAPER_OVERDRIVE = 8;
export const DEFAULT_WAVE_SHAPER_FUZZ = 40;

export const DEFAULT_PANNER_PANNING_MODEL: PanningModelType = 'equalpower';
export const DEFAULT_PANNER_DISTANCE_MODEL: DistanceModelType = 'inverse';
export const DEFAULT_PANNER_POSITION_X = 0;
export const DEFAULT_PANNER_POSITION_Y = 0;
export const DEFAULT_PANNER_POSITION_Z = -1;
export const DEFAULT_PANNER_ORIENTATION_X = 0;
export const DEFAULT_PANNER_ORIENTATION_Y = 0;
export const DEFAULT_PANNER_ORIENTATION_Z = 1;
export const DEFAULT_PANNER_REF_DISTANCE = 1;
export const DEFAULT_PANNER_MAX_DISTANCE = 10000;
export const DEFAULT_PANNER_ROLLOFF_FACTOR = 0;
export const DEFAULT_PANNER_CONE_INNER_ANGLE = 360;
export const DEFAULT_PANNER_CONE_OUTER_ANGLE = 360;
export const DEFAULT_PANNER_CONE_OUTER_GAIN = 0;

export const DEFAULT_REVERB_PRESET: BuiltInReverbPreset = 'bathroom';
export const DEFAULT_REVERB_MIX = 0;
export const DEFAULT_REVERB_EARLY_REFLECTION_DELAY = 0.01;
export const DEFAULT_REVERB_EARLY_REFLECTION_GAIN = 0.2;
export const DEFAULT_REVERB_EARLY_REFLECTION_PHASE = 0;
export const DEFAULT_REVERB_LATE_TAIL_DELAY = 0.02;
export const DEFAULT_REVERB_LATE_TAIL_DURATION = 0.5;
export const DEFAULT_REVERB_LATE_TAIL_AMPLITUDE = 0.01;
export const DEFAULT_REVERB_LATE_TAIL_ALPHA = 0.0005;
